### ISSUE TITLE
Add links to pages

### ISSUE THREAD

**Issue by simon-asp** [destefanis/figma-table-of-contents#5]
Hi! Maybe I'm misunderstanding this, but is it possible to get automatic links to the pages in my project?

It looks like the headings here are underlined which looks like links to me.
![image](https://user-images.githubusercontent.com/20322882/100989262-f2143b00-3550-11eb-9ad7-a349100ba1eb.png)

But when I run the plugin I only get headers with no links.

**Comment by megaroeny** [comment]
> Hi! Maybe I'm misunderstanding this, but is it possible to get automatic links to the pages in my project?
> 
> It looks like the headings here are underlined which looks like links to me.
> ![image](https://user-images.githubusercontent.com/20322882/100989262-f2143b00-3550-11eb-9ad7-a349100ba1eb.png)
> 
> But when I run the plugin I only get headers with no links.

You're supposed to hyperlink the text layers yourself, to your own frames. 😉 Select the text, and click the 🔗 icon at the top toolbar in the Figma UI, or hit `Cmd/Ctrl + K`

**Comment by destefanis** [comment]
Sadly yeah the API doesn't support me copying links to private files.
